export const listOrdersActionType = {
  ON_RESET_FILTERS: "ON_RESET_FILTERS",
  ON_SELECT_STATUS: "ON_SELECT_STATUS",
  ON_SELECT_APPROVAL_STATUS: "ON_SELECT_APPROVAL_STATUS",
  ON_CHANGE_ORDER_ID: "ON_CHANGE_ORDER_ID",
  ON_CHANGE_COMPANY_NAME: "ON_CHANGE_COMPANY_NAME",
};

export const customersListActionTypes = {
  ON_RESET_FILTERS: "ON_RESET_FILTERS",
  ON_SELECT_STATUS: "ON_SELECT_STATUS",
  ON_SELECT_APPROVAL_STATUS: "ON_SELECT_APPROVAL_STATUS",
  ON_CHANGE_ORDER_ID: "ON_CHANGE_ORDER_ID",
  ON_CHANGE_COMPANY_NAME: "ON_CHANGE_COMPANY_NAME",
};

export const apiStatusConstants = {
  INITIAL: "INITIAL",
  LOADING: "LOADING",
  SUCCESS: "SUCCESS",
  FAILURE: "FAILURE",
};

export const setCurrentUser = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
};
